Feature/similar components mobile/desktop update
baza-trainee/feeda pull request #3
Opened 2023-07-03 21:43 UTC by DStukalo

2023-07-09 16:14 UTC, MaksVibe commented
We are working from "client" directory. You've placed project at the root. Please place your changes in "client" directory for us to make the merge. Thanks

2023-07-10 10:59 UTC, MaksVibe commented
Rename button component pls
![Screenshot 2023-07-10 at 13 59 03](https://github.com/baza-trainee/feeda/assets/90103151/c6d4034f-e0e9-4371-8d85-3bd16468189f)

2023-07-11 04:33 UTC, MaksVibe requested changes

2023-07-11 04:33 UTC, MaksVibe commented on client/components/Button/Button.styles.ts
> +	border: none;
pls, fix broder to   `  border: 1px solid transparent;`

2023-07-11 04:33 UTC, MaksVibe commented on client/components/Label/Label.tsx
> +	isSuccess: boolean;
`isError` and `isSuccess` are optional props, fix ps

2023-07-11 04:33 UTC, MaksVibe commented on client/components/Title/Title.tsx
>  };
Set h2 for modal title pls as shown below

![Screenshot 2023-07-10 at 13 56 21](https://github.com/baza-trainee/feeda/assets/90103151/8f9e3ae0-0dd4-4deb-a7c3-3fe8331083ea)

2023-07-11 08:58 UTC, DStukalo commented on client/components/Label/Label.tsx
> +	isSuccess: boolean;
I think we need to directly set our component state, I'll rework it to reduce the number of props passed

2023-07-11 09:00 UTC, DStukalo commented on client/components/Title/Title.tsx
>  };
But we don't have h1 in our landing

2023-07-11 09:02 UTC, MaksVibe requested changes

2023-07-11 09:02 UTC, MaksVibe commented on client/components/Label/Label.tsx
> +	isSuccess: boolean;
Then, why those props are supposed to be here?

2023-07-20 17:29 UTC, MaksVibe approved these changes

2023-07-20 17:30 UTC, merged