Alpha showoff version
baza-trainee/feeda pull request #34
Opened 2023-08-14 15:56 UTC by tipanazar

2023-08-28 08:47 UTC, MaksVibe requested changes, later dismissed

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/components/TestFrom.tsx
> +    console.log(data);
You have some code issues in the code
![Screenshot 2023-08-28 at 10 55 07](https://github.com/baza-trainee/feeda/assets/90103151/d646f83b-fcc2-4b27-b7c9-fb9a4fd19f5a)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/components/TestFrom.tsx
> +        options={promiseOptions}
![Screenshot 2023-08-28 at 10 57 14](https://github.com/baza-trainee/feeda/assets/90103151/635a6302-c4cf-4fbf-b6b0-90b841a09d3b)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/app/page.tsx
Do we need here the changes?

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/components/CardsContent/CardsContent.tsx
Fix code issues pls
![Screenshot 2023-08-28 at 11 15 43](https://github.com/baza-trainee/feeda/assets/90103151/4a82fe57-b90b-48b5-8dea-df896991bdbf)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/components/Input/Input.styles.ts
>      & + label#support-label {
is the code working properly?
![Screenshot 2023-08-28 at 11 33 54](https://github.com/baza-trainee/feeda/assets/90103151/fc16b124-8ef8-4531-8eb0-a36d090bd0a4)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/components/Input/Input.tsx
Fix the following issues
![Screenshot 2023-08-28 at 11 34 58](https://github.com/baza-trainee/feeda/assets/90103151/b5728068-9fd1-40a9-a8b9-3c90e4a5b7b0)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/components/ParticipantsForm/ParticipantsForm.styles.ts
> +      /* margin-bottom: 16px; */
do we need the commented code?

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/components/ParticipantsForm/ParticipantsForm.tsx
Fix the code issues
![Screenshot 2023-08-28 at 11 36 31](https://github.com/baza-trainee/feeda/assets/90103151/b7bd2141-5aae-4ec6-be1d-f388c4dd86f1)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/components/PopUp/PopUp.tsx
Fix the issues
![Screenshot 2023-08-28 at 11 37 24](https://github.com/baza-trainee/feeda/assets/90103151/c4673e1f-eb44-4d40-8bbd-b87c291e0e44)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/components/SelectField/SelectField.tsx
Fix the issues
![Screenshot 2023-08-28 at 11 38 08](https://github.com/baza-trainee/feeda/assets/90103151/9a1267c9-ea19-4c7e-9d1c-52e8d604b01e)
![Screenshot 2023-08-28 at 11 38 14](https://github.com/baza-trainee/feeda/assets/90103151/91bc6222-1401-439d-a7cc-72016cdfca31)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/components/TestFrom.tsx
Fix the issues
![Screenshot 2023-08-28 at 11 39 46](https://github.com/baza-trainee/feeda/assets/90103151/42c149dd-3b6b-40a9-9d96-1ab3b4415190)

![Screenshot 2023-08-28 at 11 39 37](https://github.com/baza-trainee/feeda/assets/90103151/764de54a-ea93-4d7a-ac7a-49744ee63bbd)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/helpers/manageParticipantFormValues.ts
Fix the issues
![Screenshot 2023-08-28 at 11 40 34](https://github.com/baza-trainee/feeda/assets/90103151/8a441e36-840d-45ec-8310-e0d2b119e493)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/redux/participants/operations.ts
Fix the types issues
![Screenshot 2023-08-28 at 11 42 10](https://github.com/baza-trainee/feeda/assets/90103151/10900b1b-3063-478f-bc37-fbc70c8ff538)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/redux/participants/reducer.ts
Fix the issues
![Screenshot 2023-08-28 at 11 44 37](https://github.com/baza-trainee/feeda/assets/90103151/db4b1081-141b-440c-a26d-d8a9d4157cd9)

2023-08-28 08:47 UTC, MaksVibe commented on cms/src/redux/projects/projects.slice.ts
Fix the issue
![Screenshot 2023-08-28 at 11 46 14](https://github.com/baza-trainee/feeda/assets/90103151/1eb2be98-1198-447d-9286-2f809cf16756)

2023-08-28 13:02 UTC, tipanazar commented on cms/src/redux/projects/projects.slice.ts
projects is not mine part

2023-08-28 13:55 UTC, tipanazar commented on cms/src/components/SelectField/SelectField.tsx
this is not mine

2023-08-29 08:44 UTC, maxkulbako approved these changes

2023-08-29 08:46 UTC, maxkulbako approved these changes

2023-08-29 08:47 UTC, merged